global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'product_search'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8080']
